apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: taskd
  namespace: services
spec:
  selector:
    matchLabels:
      app: taskd
  serviceName: "taskd"
  replicas: 1
  template:
    metadata:
      labels:
        app: taskd
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
      - name: gitlab
      containers:
      - name: taskd
        image: foo.bar/k8s/setup/taskd:latest
        imagePullPolicy: "Always"
        env:
        - name: TASKDDATA
          value: "/data/taskd"
        volumeMounts:
        - name: data
          mountPath: /data/taskd
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "manual-taskd"
      resources:
        requests:
          storage: 200Mi

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: taskd
  labels:
    type: local
spec:
  storageClassName: manual-taskd
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/taskd #you can put your taskwarrior certs and files here, and init from the host if you want
    type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: taskd
  labels:
    app: taskd
  namespace: services
spec:
  ports:
  - port: 53589
    targetPort: 53589
    nodePort: 30001
    name: taskd
  type: "NodePort"
  selector:
    app: taskd
