FROM registry.fedoraproject.org/fedora-minimal
RUN microdnf install -y taskd && \
    microdnf -y clean all

COPY run.sh /app/taskd/

# Set the data location
#ARG TASKDDATA
#ENV TASKDDATA ${TASKDDATA:-/var/taskd}

# Configure container
#VOLUME ["${TASKDDATA}"]
EXPOSE 53589
#ENTRYPOINT ["/app/taskd/run.sh"]
